import type { Metadata } from "next"; // Import the Metadata type from the next package.
import localFont from "next/font/local"; // Import the localFont function from the next/font/local package.
import "./globals.css"; // Import the global CSS styles.
import '@mantine/core/styles.css'; // Import the Mantine core styles.

import { ColorSchemeScript, MantineProvider } from '@mantine/core'; // Import the ColorSchemeScript and MantineProvider components from the Mantine core package.

const geistSans = localFont({ // Create a local font named geistSans.
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({ // Create a local font named geistMono.
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = { // Export the metadata object.
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ // Export the RootLayout component.
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
